POST https://recommend.coffee/catalog/products
Accept: application/json
Content-Type: application/json

{
    "name": "Organic French Roast",
    "description": "Big-bodied and sweet, this dark-roasted blend features plenty of roastiness with a chocolaty body and caramel sweetness to bring it all together.",
    "variants": [
        { "weight": "310", "unitPrice": "22.40" }
    ]
}