POST https://recommend.coffee/shipping/orders
Content-Type: application/json
Accept: application/json

{
    "customerId": "2748dbf0-d494-4be1-8618-3917021d55a7",
    "firstName": "John",
    "lastName": "Doe",
    "street": "Main Street",
    "houseNumber": "123",
    "postalCode": "12345",
    "city": "Some City",
    "countryCode": "NL",
    "orderItems": [
        { "productId": "d6968a49-b8ed-44ec-8048-69e7c6a4d4be", "amount": 1, "description": "Simply awesome coffee" }
    ]
}