CREATE DATABASE profile;
GRANT ALL PRIVILEGES ON DATABASE profile TO postgres;

CREATE DATABASE payments;
GRANT ALL PRIVILEGES ON DATABASE payments TO postgres;

CREATE DATABASE registration;
GRANT ALL PRIVILEGES ON DATABASE payments TO postgres;