global using Baseline.Dates;
global using Jasper;
global using Jasper.ErrorHandling;
global using Jasper.Persistence.Marten;
global using Jasper.RabbitMQ;
global using Marten;
global using Marten.Events.Daemon.Resiliency;
global using Marten.Exceptions;
global using Npgsql;
global using Weasel.Core;
global using TastyBeans.Registration.Api.Infrastructure.Clients.Profile;
global using TastyBeans.Registration.Api.Infrastructure.Clients.Payments;
global using static TastyBeans.Registration.Api.Infrastructure.Clients.Policies;
